### ISSUE TITLE
Small overlap in buttons control pane

### ISSUE THREAD

**Issue by tdurham86** [CSE512-15S/fp-tdurham-ajh24-chaisson-ningli30#12]
The collapsible control pane mostly works well for me, but I get some overlap of the buttons to add/remove highlight controls. In particular, the remove buttons don't fit on the same line as the drop-down menus, so the tiny remove button gets its own line below the drop-down and overlaps a bit with the add highlight controls button. I'm using Opera, so it's possible this is some small cross-browser issue, but if there is a way to properly scale things in css it would be nice.

**Comment by andrewhill157** [comment]
This should be fixed now -- can reopen if this turns out not to be the case.
