### ISSUE TITLE
reset view button is broken

### ISSUE THREAD

**Issue by tdurham86** [CSE512-15S/fp-tdurham-ajh24-chaisson-ningli30#25]
This is possibly related to the difficulties with the buttons to jump to different view points. If you load the vis, move the 3D plot with the mouse, and then click the Reset View button, nothing happens.

I didn't explore this in much more detail, but I found that if I clicked on the small multiples to jump to a view and then clicked the Reset View button it would work. Although after that the small multiples buttons were broken. So right now it seems like the small multiples and Reset View functions are more or less mutually exclusive.

**Comment by andrewhill157** [comment]
This should be fixed now with 334402beafbc2d8ec5f23b7c56ea8a328dccbe58. Feel free to reopen if you find problems.
