### ISSUE TITLE
Fix E MS lineage ordering

### ISSUE THREAD

**Issue by andrewhill157** [CSE512-15S/fp-tdurham-ajh24-chaisson-ningli30#5]
All lineages are currently in the correct locations except for the E and MS lineages (or maybe a sublineage, I can't remember). The tree plots things in the order of the provided list of nodes, so we just need a way of swapping these two.

**Comment by tdurham86** [comment]
Added a comparator function to properly sort cell names according to the canonical ordering of lineage branches. Bug Fixed. Closing issue.
